io.openliberty.server.hostname=gameservice
io.openliberty.server.port=9080

# Physical Hardware 
io.openliberty.spacerover.ip=192.168.0.115
io.openliberty.spacerover.port=5045
io.openliberty.gameboard.ip=192.168.0.117
io.openliberty.gameboard.port=5045

# Test
#io.openliberty.spacerover.ip=mockrover
#io.openliberty.spacerover.port=5045
#io.openliberty.gameboard.ip=mockboard
#io.openliberty.gameboard.port=5045

# Free Roam Mode
io.openliberty.freeroam.ms_per_degree=8
io.openliberty.freeroam.ms_per_cm=18
io.openliberty.freeroam.max_duration_ms=30000
io.openliberty.freeroam.max_step_duration_ms=10000