version: "3.9"
services:
    gameservice:
        build: ./game
        ports:
            - "9070:9080"
    client:
        build:
            context: ./client
            args:
                - GAME_URL=http://localhost:9070/game
                - GAME_SOCKET_URL=ws://localhost:9070/roversocket
        ports:
            - "3000:80"
    mockrover:
        build: ./mock/rover
        ports:
            - "5045:5045"
    mockboard:
        build: ./mock/board
        ports:
            - "5046:5045"
